[package]
name = "contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.15.0" }
starknet = "2.9.1"

[cairo]
sierra-replace-ids = false

[dev-dependencies]
cairo_test = "2.9.1"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
