name: PR - vite-hardhat
on:
  pull_request:
    paths:
      - 'vite-hardhat/**'

jobs:
  test-vite-hardhat:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vite-hardhat

    steps:
      - uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Get latest version
        id: versions_step
        run: |
          output=$(node ../.github/scripts/latest.js)
          echo "Output from Node.js script: $output"

          STABLE=$(echo $output | jq -r '.stable')
          echo "::set-output name=stable::$STABLE"

      - name: Install dependencies
        run: bun install

      - name: Compile
        run: bunx hardhat compile

      - name: Run tests
        run: bun run test
